version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: blort
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: